version: "3.9"
services:
  rabbitmq:
    image: rabbitmq:3.9-management-alpine #management version needed to be able to have a User interface
    container_name: rabbitmq
    environment:
        - RABBITMQ_DEFAULT_USER=DistribtAdmin
        - RABBITMQ_DEFAULT_PASS=DistribtPass
    ports:
        - 5672:5672
        - 15672:15672
    volumes: 
          - ./tools/rabbitmq/rabbitmq.config:/etc/rabbitmq/rabbitmq.config
          - ./tools/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json
  consul:
    container_name: consul
    image: consul
    ports:
      - 8500:8500 # this is the UI/API calls
      - 8400:8400
      - 8600:8600
      - 8600:8600/udp
  vault:
    image: vault:latest
    container_name: vault
    ports:
      - 8200:8200
    environment:
      VAULT_ADDR: "http://127.0.0.1:8200"
      # in production scenarios the token mechanisim for loggin will be forbidden,
      # it cannot be in source control.
      VAULT_TOKEN: "vault-distribt-token" # to be able to use the cli on dev
      VAULT_DEV_ROOT_TOKEN_ID: "vault-distribt-token"
    cap_add:
      - IPC_LOCK
    depends_on:
      - rabbitmq
      - consul
